Add dlist.gg
botblock/data pull request #38
Opened 2022-07-14 00:30 UTC by advaith1

2022-07-14 01:21 UTC, MattIPv4 requested changes

2022-07-14 01:21 UTC, MattIPv4 commented on data/lists/discordlist.gg.json
> +    "added": 1542972675,
This timestamp doesn't seem correct? It should be "now" to represent when the list is added to BotBlock

2022-07-14 01:21 UTC, advaith1 commented on data/lists/discordlist.gg.json
> +    "added": 1542972675,
oops didnt see that

2022-07-14 01:22 UTC, MattIPv4 approved these changes
LGTM, ty

2022-07-14 01:23 UTC, merged

2022-07-16 02:14 UTC, CircuitSacul commented
Gives a 405: Method not allowed.

I assume this is because discordlist wants PUT requests, not POST requsts.

<img width="553" alt="Screen Shot 2022-07-15 at 10 13 57 PM" src="https://user-images.githubusercontent.com/55721663/179334842-d1b8052f-8a3f-4b43-acd8-ea0221dc34b0.png">

2022-07-16 02:15 UTC, renhiyama commented
I love how everyone uses different methods and "methods"

2022-07-16 02:21 UTC, MattIPv4 commented
@CircuitSacul Please could open an issue over in the api-worker for this? I suspect we'll need to add a new api_method property or similar and add support for that in the worker.