Update everything to support api_post_method
botblock/data pull request #48
Opened 2022-08-08 02:29 UTC by A5rocks

Fixes https://github.com/botblock/data/issues/45

2022-08-08 11:17 UTC, MattIPv4 requested changes
A few small wording tweaks :)

2022-08-08 11:17 UTC, MattIPv4 commented on schema/list.json
>              "title": "List API guild count POST endpoint",
```suggestion
            "title": "List API guild count submission endpoint",
```

2022-08-08 11:17 UTC, MattIPv4 commented on schema/list.json
>              "description": "The endpoint URL for posting a bot's guild count to the list, if known, with `:id` as placeholder for bot Id."
```suggestion
            "description": "The endpoint URL for submitting a bot's guild count to the list, if known, with `:id` as placeholder for bot Id."
```

2022-08-08 11:17 UTC, MattIPv4 commented on schema/list.json
> +            "title": "List API guild count method to use",
```suggestion
            "title": "List API guild count HTTP method",
```

2022-08-08 11:17 UTC, MattIPv4 commented on schema/list.json
> +            "description": "The method to use for submitting a bot's guild count to the list via `api_post`."
```suggestion
            "description": "The HTTP method to use for submitting a bot's guild count to the list via `api_post`. Defaults to `POST` if null."
```

2022-08-08 11:23 UTC, MattIPv4 requested changes
Ah! And the OpenAPI schema needs updating too please :) The [examples](https://github.com/botblock/data/blob/acffab0fe6baa8f79ea676f75367f41696f44cd9/openapi.yml#L348) and the [list schema](https://github.com/botblock/data/blob/acffab0fe6baa8f79ea676f75367f41696f44cd9/openapi.yml#L551) will need this new prop

2022-08-21 18:43 UTC, MattIPv4 commented
@A5rocks Apologies for the delay here -- it looks like you've got one conflict that needs resolving.

2022-08-22 05:26 UTC, A5rocks commented
Alright, thanks! Should be fixed now.

2022-08-22 11:06 UTC, MattIPv4 approved these changes
LGTM

2022-08-22 11:06 UTC, merged