Added Topiclist
botblock/data pull request #55
Opened 2022-08-28 07:27 UTC by Miya25

Added Topiclist

2022-08-28 11:20 UTC, Andre601 commented on data/lists/topiclist.xyz.json
> +    "discord_only": 0,
Is the list only listing discord bots? Then this should be 1

2022-08-28 11:28 UTC, MattIPv4 requested changes
You have multiple CI failures that need addressing:

- You are missing the `$schema` property
- You are missing the `added` property
- You have included invalid items in `features`
- You have line-endings that do not match the editorconfig for the repo

2022-08-28 11:28 UTC, MattIPv4 commented on data/lists/topiclist.xyz.json
> +    "api_get": "https://topiclist.xyz/api/bots/:botID",
```suggestion
    "api_get": "https://topiclist.xyz/api/bots/:id",
```
The placeholder for the bot ID should always be `:id`

2022-08-28 12:12 UTC, Miya25 commented
hmm it should work now..

2022-08-28 12:14 UTC, Miya25 commented on data/lists/topiclist.xyz.json
> +    "discord_only": 0,
but it also have serverlisting..

2022-08-28 14:15 UTC, Andre601 commented on data/lists/topiclist.xyz.json
> +    "discord_only": 0,
The option is not about if you only allow discord bots, but if you only allow discord-related content.
If your site is also listing servers and bots from other services (i.e. revolt.chat) would this being 0 be okay. But if your site only allows discord-related stuff then it has to be 1. It's that simple.

2022-10-02 06:15 UTC, Miya25 commented
@MattIPv4 any updates on this?

2022-10-02 14:35 UTC, MattIPv4 commented
@Miya25 You still have CI failures, the same CI failures from over a month ago. If you do not solve them, I am going to have to close this PR due to a lack of progress.

2022-10-03 02:24 UTC, Miya25 commented
hmm i am trying to some it but idk whats causing it

2022-10-03 13:31 UTC, MattIPv4 commented
As the CI errors note:

1. Your file does not match the editorconfig for this repo, check that your line endings are correct.

2. You are missing the `added` property from your file, which is required per the schema.

3. You have listed features for your list that are not recognised features on BotBlock, based on [data/features](https://github.com/botblock/data/tree/master/data/features).

4. You are missing the `$schema` property from your file.

2022-11-20 15:03 UTC, MattIPv4 commented
Closing, no progress.

2022-11-20 15:03 UTC, closed without merging