Update bhbotlist.tech.json
botblock/data pull request #63
Opened 2022-11-10 17:16 UTC by anshtyagi0

Updating bhbotlist features

2022-11-20 14:35 UTC, anshtyagi0 commented
Someone please merge it.

2022-11-20 15:07 UTC, MattIPv4 requested changes

2022-11-20 15:07 UTC, MattIPv4 commented on data/lists/bhbotlist.tech.json
> +        "vanity-urls-for-all",
I'm not seeing vanity URLs on your site? Everything still seems to use bot IDs?

2022-11-20 15:13 UTC, anshtyagi0 commented on data/lists/bhbotlist.tech.json
> +        "vanity-urls-for-all",
We use it for certified bots like: https://bhbotlist.tech/stella

2022-11-20 15:13 UTC, anshtyagi0 commented on data/lists/bhbotlist.tech.json
> +        "vanity-urls-for-all",
we don't change existing url

2022-11-20 15:46 UTC, MattIPv4 commented on data/lists/bhbotlist.tech.json
> +        "vanity-urls-for-all",
Okay, so if its just for certified bots, then it isn't for all bots as the feature says is it?

2022-11-20 15:47 UTC, MattIPv4 commented on data/lists/bhbotlist.tech.json
> +        "vanity-urls-for-all",
There is a separate feature if certified bots get vanity URLs, not all bots: https://github.com/botblock/data/blob/master/data/features/certified-bot-vanity-urls.json

2022-12-12 19:07 UTC, MattIPv4 commented
No progress, closing.

2022-12-12 19:07 UTC, closed without merging