Add VitalList.xyz
botblock/data pull request #64
Opened 2022-11-15 01:06 UTC by BrydenIsNotSmart

2022-11-20 15:44 UTC, anshtyagi0 submitted a review, later dismissed

2022-11-20 15:51 UTC, MattIPv4 requested changes

2022-11-20 15:51 UTC, MattIPv4 commented on data/lists/vitallist.xyz.json
> +        "has-search",
Where is the search on your site?

2022-11-20 15:51 UTC, MattIPv4 commented on data/lists/vitallist.xyz.json
> +        "iframe-long-description",
Your list doesn't support iframe descriptions? You allow Markdown and a very limited subset of HTML it seems

2022-11-20 18:36 UTC, BrydenIsNotSmart commented on data/lists/vitallist.xyz.json
> +        "iframe-long-description",
We do have iframe descriptions. 
![image](https://user-images.githubusercontent.com/67612593/202919693-559b09b5-5cd6-49ee-bf13-44e71a0a37a4.png)

2022-11-20 18:36 UTC, BrydenIsNotSmart commented on data/lists/vitallist.xyz.json
> +        "has-search",
Sorry, search was supposed to be added but is being delaying. I'll remove it.

2022-11-21 12:24 UTC, MattIPv4 commented on data/lists/vitallist.xyz.json
> +        "iframe-long-description",
Ah cool, I couldn't get it work render in the add bot preview, but looks good 👍

2022-11-21 12:26 UTC, MattIPv4 approved these changes

2022-11-21 12:26 UTC, merged

2022-11-22 03:05 UTC, BrydenIsNotSmart commented on data/lists/vitallist.xyz.json
> +        "iframe-long-description",
I think we updated the bot descriptions for the bot page but not the previews, I will look into that.