Updated infinity bots with passing tests 😌
botblock/data pull request #69
Opened 2023-02-28 20:55 UTC by TheRealToxicDev

2023-02-28 20:57 UTC, TheRealToxicDev commented
I removed all old legacy data hopefully this change won’t reflect negatively on the site. However if I need to readd them I can 👌🏻

2023-02-28 22:45 UTC, MattIPv4 requested changes

2023-02-28 22:45 UTC, MattIPv4 commented on data/legacy.json
> -    "infinitybots.com": "infinitybotlist.com",
You need to keep these existing legacy items but change the values to be the new ID -- removing them will break users that are currently using these old IDs still

2023-02-28 22:45 UTC, MattIPv4 commented on data/legacy.json
> +    "infinitybots.gg": "infinitybots.gg",
A legacy ID cannot map to itself, that makes no sense. This should make the old ID to the new ID (`nfinitybotlist.com` -> `infinitybots.gg`)

2023-03-01 00:16 UTC, TheRealToxicDev commented on data/legacy.json
> +    "infinitybots.gg": "infinitybots.gg",
Re-added and updated

2023-03-01 13:21 UTC, MattIPv4 requested changes

2023-03-01 13:21 UTC, MattIPv4 commented on data/legacy.json
> +    "nfinitybots.com": "infinitybots.gg",
```suggestion
    "infinitybotlist.com": "infinitybots.gg",
```

2023-03-02 02:57 UTC, TheRealToxicDev commented on data/legacy.json
> +    "nfinitybots.com": "infinitybots.gg",
Suggested change has been committed

2023-03-02 02:58 UTC, MattIPv4 approved these changes

2023-03-02 02:59 UTC, merged