Update discord.place icon
botblock/data pull request #91
Opened 2024-09-03 01:44 UTC by chimpdev

discord.place's logo has changed, so I'm changing the icon here too

2024-09-05 08:40 UTC, chimpdev commented
@MattIPv4

2024-09-11 01:44 UTC, MattIPv4 requested changes

2024-09-11 01:44 UTC, MattIPv4 commented on data/lists/discord.place.json
> +    "icon": "https://i.imgur.com/DcUjS0Y.png",
Is there any image hosted on their site we can use? Hotlinking to imgur isn't ideal and they try to prevent it now.

2024-09-11 01:50 UTC, chimpdev commented on data/lists/discord.place.json
> +    "icon": "https://i.imgur.com/DcUjS0Y.png",
Yeah https://discord.place/templates/square_logo.png

2024-09-11 01:53 UTC, MattIPv4 approved these changes

2024-09-11 01:53 UTC, merged